-- Authentication accounts. Deliberately portable SQL: the same migration runs
-- against Postgres in production and H2 in PostgreSQL mode under test, so the
-- schema the tests exercise is the schema that ships.
--
-- password_hash is nullable and email exists from the start so a federated
-- (Google) account is just a row with no hash, and adding it needs no migration.
CREATE TABLE app_user (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL,
    email         VARCHAR(255),
    password_hash VARCHAR(100),
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('AGENT', 'ADMIN'))
);

-- Google sign-in will look accounts up by email rather than username.
CREATE INDEX ix_app_user_email ON app_user (email);
