package com.capstone.crm.observability;

import com.capstone.crm.security.JwtService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.not;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The info endpoint, from both sides of the door.
 *
 * The connection panel reads this while signed in; a scanner probing actuator
 * paths is anonymous. The endpoint names the database target, the topic and
 * the revision, so the two callers must see very different things: everything
 * and nothing.
 */
@SpringBootTest
@AutoConfigureMockMvc
class ConnectionInfoTest {

    @Autowired MockMvc mockMvc;
    @Autowired JwtService jwtService;

    @Test
    void anonymousCallerIsRefused() throws Exception {
        mockMvc.perform(get("/actuator/info"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void agentSeesTheConnections() throws Exception {
        mockMvc.perform(get("/actuator/info")
                        .header("Authorization", "Bearer "
                                + jwtService.issueToken("agent1", "AGENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.connections.profile").value("test"))
                // No platform signal under the suite, so the profile is the
                // derived environment.
                .andExpect(jsonPath("$.connections.environment").value("profile: test"))
                // The database's NAME, never a URL: no host, no port, no
                // connection parameters.
                .andExpect(jsonPath("$.connections.database").value("crm (in-memory)"))
                .andExpect(content().string(not(containsString("MODE=PostgreSQL"))))
                .andExpect(content().string(not(containsString("jdbc:"))))
                .andExpect(jsonPath("$.connections.kafka.topic").value("crm.interaction.v1"))
                .andExpect(jsonPath("$.connections.kafka.consumerGroup")
                        .value("crm-interaction-service-v1"))
                // The address never appears anywhere in the payload.
                .andExpect(jsonPath("$.connections.kafka.bootstrap").doesNotExist())
                .andExpect(content().string(not(containsString("localhost"))))
                // The in-depth block the panel's collapsible section renders.
                .andExpect(jsonPath("$.runtime.java.version").exists())
                .andExpect(jsonPath("$.runtime.dependencies.springBoot").exists())
                .andExpect(jsonPath("$.runtime.dependencies.hibernate").exists())
                .andExpect(jsonPath("$.runtime.os.name").exists())
                // build-info.properties is generated by the build-info goal, so
                // the version the panel shows is the version Maven built.
                .andExpect(jsonPath("$.build.version").exists())
                // No password appears anywhere in the payload, whatever shape
                // future URLs take.
                .andExpect(content().string(not(containsString("password"))));
    }

    @Test
    void environmentIsDerivedFromThePlatformNeverDeclared() throws Exception {
        // Kubernetes: the injected variable plus the mounted namespace file.
        var env = new org.springframework.mock.env.MockEnvironment()
                .withProperty("KUBERNETES_SERVICE_HOST", "10.43.0.1");
        java.nio.file.Path ns = java.nio.file.Files.createTempFile("ns", "");
        java.nio.file.Files.writeString(ns, "student02\n");
        assertThat(ConnectionInfoContributor.environmentName(env, ns, "local"))
                .isEqualTo("kubernetes: student02");

        // The variable without the mount still names the platform.
        assertThat(ConnectionInfoContributor.environmentName(
                env, ns.resolveSibling("missing"), "local"))
                .isEqualTo("kubernetes");

        // No platform signal: the profile is the honest answer.
        assertThat(ConnectionInfoContributor.environmentName(
                new org.springframework.mock.env.MockEnvironment(), ns, "local"))
                .isEqualTo("profile: local");
    }

    @Test
    void databaseNamesCarryNoAddress() {
        assertThat(ConnectionInfoContributor.databaseName(
                "jdbc:postgresql://100.22.136.97:5432/bootcamp?currentSchema=student02"))
                .isEqualTo("bootcamp");
        assertThat(ConnectionInfoContributor.databaseName(
                "jdbc:postgresql://localhost:5432/crm"))
                .isEqualTo("crm");
        assertThat(ConnectionInfoContributor.databaseName(
                "jdbc:h2:mem:crm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"))
                .isEqualTo("crm (in-memory)");
        assertThat(ConnectionInfoContributor.databaseName("")).isEmpty();
    }

    @Test
    void schemaParameterIsExtractedWhenPresent() {
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/bootcamp?currentSchema=student02"))
                .isEqualTo("student02");
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/crm?sslmode=require&currentSchema=s04"))
                .isEqualTo("s04");
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/crm")).isNull();
    }

}
