package com.capstone.crm.observability;

import com.capstone.crm.security.JwtService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.not;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The info endpoint, from both sides of the door.
 *
 * The connection panel reads this while signed in; a scanner probing actuator
 * paths is anonymous. The endpoint names the database target, the topic and
 * the revision, so the two callers must see very different things: everything
 * and nothing.
 */
@SpringBootTest
@AutoConfigureMockMvc
class ConnectionInfoTest {

    @Autowired MockMvc mockMvc;
    @Autowired JwtService jwtService;

    @Test
    void anonymousCallerIsRefused() throws Exception {
        mockMvc.perform(get("/actuator/info"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void agentSeesTheConnections() throws Exception {
        mockMvc.perform(get("/actuator/info")
                        .header("Authorization", "Bearer "
                                + jwtService.issueToken("agent1", "AGENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.connections.profile").value("test"))
                // The test datasource, with its parameters cut: MODE=PostgreSQL
                // and DB_CLOSE_DELAY configure the connection, they do not
                // identify the target.
                .andExpect(jsonPath("$.connections.database").value("h2:mem:crm"))
                .andExpect(content().string(not(containsString("MODE=PostgreSQL"))))
                .andExpect(jsonPath("$.connections.kafka.topic").value("crm.interaction.v1"))
                .andExpect(jsonPath("$.connections.kafka.consumerGroup")
                        .value("crm-interaction-service-v1"))
                // build-info.properties is generated by the build-info goal, so
                // the version the panel shows is the version Maven built.
                .andExpect(jsonPath("$.build.version").exists())
                // No password appears anywhere in the payload, whatever shape
                // future URLs take.
                .andExpect(content().string(not(containsString("password"))));
    }

    @Test
    void schemaParameterIsExtractedWhenPresent() {
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/bootcamp?currentSchema=student02"))
                .isEqualTo("student02");
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/crm?sslmode=require&currentSchema=s04"))
                .isEqualTo("s04");
        assertThat(ConnectionInfoContributor.schemaParameter(
                "jdbc:postgresql://host:5432/crm")).isNull();
    }

    @Test
    void jdbcUrlsAreSanitizedToTheirTarget() {
        assertThat(ConnectionInfoContributor.sanitizeJdbcUrl(
                "jdbc:postgresql://db.example.com:5432/crm?sslmode=require&currentSchema=student02"))
                .isEqualTo("postgresql://db.example.com:5432/crm");
        assertThat(ConnectionInfoContributor.sanitizeJdbcUrl(
                "jdbc:h2:mem:crm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"))
                .isEqualTo("h2:mem:crm");
        // Never our shape, but the sanitizer must hold anyway.
        assertThat(ConnectionInfoContributor.sanitizeJdbcUrl(
                "jdbc:postgresql://user:secret@host:5432/crm"))
                .isEqualTo("postgresql://host:5432/crm");
        assertThat(ConnectionInfoContributor.sanitizeJdbcUrl("")).isEmpty();
    }
}
